/**
 * NOTICE: DO NOT MODIFY THIS FILE!
 * The contents of this file were automatically generated by
 * the 'ng generate @skyux/i18n:lib-resources-module modules/shared/sky-errors' schematic.
 * To update this file, simply rerun the command.
 */

import { NgModule } from '@angular/core';
import {
  getLibStringForLocale,
  SkyAppLocaleInfo,
  SkyI18nModule,
  SkyLibResources,
  SkyLibResourcesProvider,
  SKY_LIB_RESOURCES_PROVIDERS
} from '@skyux/i18n';

const RESOURCES: { [locale: string]: SkyLibResources } = {
  'EN-US': {"skyux_errors_broken_description":{"message":"Try to refresh this page or come back later."},"skyux_errors_broken_title":{"message":"Sorry, something went wrong."},"skyux_errors_construction_description":{"message":"Thanks for your patience while improvements are made! \n Please check back in a little while."},"skyux_errors_construction_title":{"message":"This page will return soon."},"skyux_errors_not_found_title":{"message":"Sorry, we can't reach that page."},"skyux_errors_security_title":{"message":"This page requires additional permissions."}},
};

export class SkyErrorsResourcesProvider implements SkyLibResourcesProvider {
  public getString(localeInfo: SkyAppLocaleInfo, name: string): string {
    return getLibStringForLocale(RESOURCES, localeInfo.locale, name);
  }
}

/**
 * Import into any component library module that needs to use resource strings.
 */
@NgModule({
  exports: [SkyI18nModule],
  providers: [{
    provide: SKY_LIB_RESOURCES_PROVIDERS,
    useClass: SkyErrorsResourcesProvider,
    multi: true
  }]
})
export class SkyErrorsResourcesModule { }
